// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../sources/zz/deps.js", [], []);
goog.addDependency("../../../../sources/zz/base.js", ['zz'], ['zz._stylesheet.remap', 'zz.demos.App']);
goog.addDependency("../../../../sources/zz/_stylesheet/remap.js", ['zz._stylesheet.remap'], []);
goog.addDependency("../../../../sources/zz/demos/index.js", ['zz.demos.App'], ['goog.dom', 'goog.events', 'zz.template', 'zz.model.Set', 'zz.model.Example1', 'zz.model.Example2', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/_template/test.js", ['zz.template'], ['soy', 'soydata']);
goog.addDependency("../../../../sources/zz/model/fieldtypes.js", ['zz.model.FieldTypes'], []);
goog.addDependency("../../../../sources/zz/model/example1.js", ['zz.model.Example1'], ['zz.model.Row', 'zz.model.IRow', 'zz.model.FieldTypes', 'zz.model.Example2']);
goog.addDependency("../../../../sources/zz/model/rowdeleteevent.js", ['zz.model.RowDeleteEvent'], ['goog.events.Event', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/model/error.js", ['zz.model.Error'], []);
goog.addDependency("../../../../sources/zz/model/eventtype.js", ['zz.model.EventType'], ['goog.events']);
goog.addDependency("../../../../sources/zz/model/rowcreateevent.js", ['zz.model.RowCreateEvent'], ['goog.events.Event', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/model/model.js", ['zz.model'], ['goog.async.run', 'zz.model.Error', 'zz.model.Set', 'zz.model.RowUpdateEvent']);
goog.addDependency("../../../../sources/zz/model/irow.js", ['zz.model.IRow'], []);
goog.addDependency("../../../../sources/zz/model/set.js", ['zz.model.Set'], ['goog.array', 'goog.async.run', 'goog.events.EventTarget', 'zz.model', 'zz.model.Error']);
goog.addDependency("../../../../sources/zz/model/rowupdateevent.js", ['zz.model.RowUpdateEvent'], ['goog.events.Event', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/model/row.js", ['zz.model.Row'], ['goog.object', 'goog.async.run', 'goog.events.EventTarget', 'zz.model', 'zz.model.Error', 'zz.model.Set', 'zz.model.IRow', 'zz.model.FieldTypes']);
goog.addDependency("../../../../sources/zz/model/example2.js", ['zz.model.Example2'], ['zz.model.Row', 'zz.model.IRow', 'zz.model.FieldTypes']);
