// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../sources/zz/base.js", ['zz'], ['zz._stylesheet.remap', 'zz.demos.App']);
goog.addDependency("../../../../sources/zz/deps.js", [], []);
goog.addDependency("../../../../sources/zz/demos/index.js", ['zz.demos.App'], ['goog.dom', 'goog.events', 'zz.template', 'zz.model.TestItem', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/_stylesheet/remap.js", ['zz._stylesheet.remap'], []);
goog.addDependency("../../../../sources/zz/model/itemdeleteevent.js", ['zz.model.ItemDeleteEvent'], ['goog.events.Event', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/model/idataitem.js", ['zz.model.IDataItem'], []);
goog.addDependency("../../../../sources/zz/model/itemcreateevent.js", ['zz.model.ItemCreateEvent'], ['goog.events.Event', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/model/itemupdateevent.js", ['zz.model.ItemUpdateEvent'], ['goog.events.Event', 'zz.model.EventType']);
goog.addDependency("../../../../sources/zz/model/eventtype.js", ['zz.model.EventType'], ['goog.events']);
goog.addDependency("../../../../sources/zz/model/testitem.js", ['zz.model.TestItem'], ['zz.model.FieldTypes', 'zz.model.IDataItem', 'zz.model.DataItem']);
goog.addDependency("../../../../sources/zz/model/dataitem.js", ['zz.model.DataItem'], ['goog.object', 'goog.async.run', 'goog.events.EventTarget', 'zz.model', 'zz.model.IDataItem', 'zz.model.FieldTypes', 'zz.model.ItemCreateEvent']);
goog.addDependency("../../../../sources/zz/model/model.js", ['zz.model'], ['goog.async.run', 'zz.model.ItemUpdateEvent']);
goog.addDependency("../../../../sources/zz/model/fieldtypes.js", ['zz.model.FieldTypes'], []);
goog.addDependency("../../../../sources/zz/_template/test.js", ['zz.template'], ['soy', 'soydata']);
