// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../sources/zz/base.js", ['zz'], ['zz._stylesheet.remap']);
goog.addDependency("../../../../sources/zz/deps.js", [], []);
goog.addDependency("../../../../sources/zz/demos/index.js", ['zz.demos.App'], ['goog.dom', 'zz._template', 'zz.model.BaseItem']);
goog.addDependency("../../../../sources/zz/_stylesheet/remap.js", ['zz._stylesheet.remap'], []);
goog.addDependency("../../../../sources/zz/model/baseitem.js", ['zz.model.BaseItem'], ['goog.array', 'goog.object', 'goog.events.EventTarget']);
goog.addDependency("../../../../sources/zz/_template/test.js", ['zz._template'], ['soy', 'soydata']);
